### ISSUE TITLE
Project pair

### ISSUE THREAD

**Issue by bagoviggo** [FabbMutua/simple_shell#1]
Hi , I'm Roy, we were paired for the simple_shell project.. Allow me to merge my work to your repo so I can be scored

**Comment by FabbMutua** [comment]
Hello Roy,
   Sorry for the late reply. I've merged the branch, though I might have
done it a few minutes late.

**Comment by bagoviggo** [comment]
Thanks Bruh, at least I got a few points cheers.

**Comment by FabbMutua** [comment]
What's the total percentage you got on your end? ( On the whole
simple_shell project?)

**Comment by FabbMutua** [comment]
Mine didn't go so well. I've sent my project in your email. This email:
***@***.***
